# Generated by Django 4.2.1 on 2023-06-04 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 16, 27, 25, 826140, tzinfo=datetime.timezone.utc)),
        ),
    ]
