# Generated by Django 4.2.1 on 2023-06-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, null=True)),
                ('real_cost', models.FloatField(blank=True, null=True)),
                ('vehicle_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rent.vehiclesize')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rent.vehicletype')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='rent.vehicle'),
            preserve_default=False,
        ),
    ]
