# Generated by Django 4.2.1 on 2023-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO_web', '0004_alter_todo_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_task',
            name='date_completion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo_task',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo_task',
            name='deadline_date',
            field=models.DateField(),
        ),
    ]
