# Generated by Django 4.2.1 on 2023-05-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TO_DO_web', '0005_alter_todo_task_date_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_task',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo_task',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
